const conteudoArquetipos = {
  "1": {
    "nome": "O Mago",
    "geral": {
      "simbolismo": "Na carta do Mago no Tarot Rider-Waite, você vê um jovem em pé diante de uma mesa que abriga os quatro elementos: a Taça (água/emoção), a Espada (ar/mente), o Ouro (terra/matéria) e o Bastão (fogo/ação). Sua mão direita aponta para o céu segurando um bastão de duas pontas, enquanto sua mão esquerda aponta para a terra. Acima de sua cabeça flutua a lemniscata (o símbolo do infinito), e ele está cercado por rosas vermelhas e lírios brancos. Este simbolismo representa o canalizador supremo: a ponte viva que puxa a inspiração divina do céu e a manifesta fisicamente na matéria na terra. As rosas e lírios simbolizam a pureza da intenção unida ao desejo apaixonado pela criação.",
      "identidade": "Seu primeiro nome carrega a assinatura vibracional do Mago. Isso significa que você é uma pessoa que possui um dom inato de manifestação, liderança e capacidade de transformar o nada em realidade. Desde a infância, você sente uma inquietação silenciosa, uma intuição clara de que não nasceu para seguir caminhos prontos, mas sim para criar suas próprias rotas. Sua mente funciona de maneira rápida e inventiva; onde os outros enxergam problemas insolúveis, você enxerga matérias-primas para uma nova solução. A sua essência é a do iniciador: aquele que acende a faísca original e lidera pelo exemplo de sua criatividade.",
      "sombra": "A sombra do Mago reside na dispersão e no medo secreto do fracasso que paralisa a sua ação. Como você enxerga muitas possibilidades e tem facilidade em aprender coisas novas, o maior perigo é a superficialidade ou a procrastinação ativa (iniciar dez projetos e não concluir nenhum). Secretamente, você pode travar por medo de expor suas criações e ser julgado. A sombra do Mago também se manifesta no orgulho intelectual ou na tentação de manipular as circunstâncias e pessoas para que as coisas aconteçam do seu jeito, em vez de permitir o fluxo natural da vida.",
      "evolucao": "Para que o Mago em você atinja seu potencial pleno de evolução, você precisa aprender a focar sua energia em um único propósito por vez. Cultive a paciência do construtor: uma grande ideia só se consolida se houver consistência e rotina. Aprenda a terminar o que começou antes de se lançar em uma nova paixão intelectual. Aceite a sua vulnerabilidade e entenda que errar no processo de criação não anula a sua inteligência, mas sim lapida a sua maestria."
    },
    "amor": {
      "comportamento": "No amor, a energia do Mago é fascinante, comunicativa e magnética. Você atrai parceiros pela sua conversa inteligente e pelo seu charme natural. Porém, você se entedia com extrema facilidade. Se o relacionamento cair na rotina ou se o parceiro tentar sufocar a sua individualidade e espaço de criação, você pode se afastar emocionalmente. O seu maior medo na vida afetiva é perder a liberdade e ser engolido por um relacionamento comum e sem estímulos intelectuais.",
      "cura": "Para curar suas dinâmicas amorosas, você precisa compreender que o amor profundo exige tempo e vulnerabilidade, não apenas atração e novidade. Evite a tendência de tentar 'controlar' racionalmente os sentimentos do outro. Permita-se ser visto sem a sua armadura de 'pessoa autossuficiente e inteligente'. A verdadeira conexão acontece quando você compartilha as suas fraquezas, e não apenas o seu brilho."
    },
    "carreira": {
      "visao": "Na vida profissional, você possui o perfil clássico do empreendedor, do solucionador de problemas complexos ou do profissional autônomo de sucesso. Você prospera em ambientes onde tem autonomia de decisão. O dinheiro para você flui a partir da sua capacidade de transformar ideias criativas em serviços ou produtos práticos. Você tem um magnetismo comercial muito forte; quando acredita no que vende, ninguém consegue resistir à sua comunicação.",
      "escassez": "Sua principal autossabotagem financeira é a falta de gestão e a impulsividade. Como você sente que sempre pode 'dar um jeito' e ganhar mais dinheiro através de uma nova ideia, você pode negligenciar a poupança, a estabilidade e o planejamento de longo prazo. A sua escassez não vem da falta de capacidade de ganho, mas do desperdício de energia financeira e da pressa por resultados imediatos."
    },
    "heranca": {
      "ancestralidade": "Carregar a energia do Mago em seu sobrenome de família revela uma herança ancestral ligada à superação de limites através da astúcia, do trabalho inteligente e do empreendedorismo. Sua linhagem familiar provavelmente sobreviveu a grandes crises através do raciocínio rápido e da capacidade de se reinventar do zero. No entanto, o padrão herdado que você precisa curar é o da desconfiança: a crença de que você só pode contar com a sua própria mente e que ninguém mais vai te ajudar. O seu clã familiar te passa a força da autossuficiência, mas você é o canal para curar o medo da escassez e a solidão do guerreiro que acha que precisa carregar o mundo nas costas sozinhos."
    }
  },
  "2": {
    "nome": "A Sacerdotisa",
    "geral": {
      "simbolismo": "A Sacerdotisa (ou A Papisa) no Tarot Rider-Waite está sentada entre duas colunas, uma preta marcada com o 'B' (Boaz - passividade, sombra) e outra branca marcada com o 'J' (Jakin - ação, luz). Ela veste mantos azuis fluidos que lembram a água, tem uma lua crescente aos seus pés e usa uma coroa de Ísis na cabeça. No seu colo, ela segura a Torá (a lei oculta), parcialmente coberta por seu manto. Atrás dela, há um véu decorado com palmeiras e romãs, que oculta as águas profundas do inconsciente. O simbolismo da Sacerdotisa fala sobre o silêncio sagrado, a sabedoria intuitiva, o mistério da alma e a capacidade de esperar a verdade emergir sem forçar as situações. Ela é a ponte entre o mundo invisível e a realidade cotidiana.",
      "identidade": "Seu primeiro nome vibra na frequência da Sacerdotisa. Isso indica que a sua essência é profunda, observadora e extremamente intuitiva. Você é aquela pessoa que capta o que não foi dito, lê a atmosfera das salas e percebe as reais intenções das pessoas antes mesmo que elas digam uma palavra. Você tem uma relação íntima com o silêncio e necessita de momentos de isolamento para recarregar sua energia. Sua sabedoria não é acadêmica; é uma sabedoria de alma, ancestral, conectada ao invisível. Pessoas frequentemente te procuram para desabafar porque sentem que você emana uma presença acolhedora e que não julga.",
      "sombra": "A sombra da Sacerdotisa se manifesta na passividade, no isolamento excessivo e no acúmulo de segredos ou ressentimentos. Você pode cair no padrão de guardar tudo para si mesma por medo de conflitos ou rejeição, tornando-se fria, inacessível ou misteriosa demais. O maior desafio da sua sombra é a omissão: saber exatamente o que precisa ser feito ou dito (pela sua intuição clara), mas escolher o silêncio por comodismo, medo de assumir a sua autoridade pessoal ou por acreditar que os outros 'não merecem' a sua sabedoria.",
      "evolucao": "O seu caminho de evolução exige que você traga a sua sabedoria intuitiva para a ação prática no mundo real. Não use o seu misticismo ou o seu isolamento como fuga dos desafios da vida real. Aprenda a expressar seus limites e sentimentos com clareza em vez de se retirar no silêncio punitivo. Confie na sua voz interior e use-a para guiar e curar os outros, ocupando ativamente o seu espaço de autoridade."
    },
    "amor": {
      "comportamento": "No amor, a Sacerdotisa é leal, misteriosa e profundamente seletiva. Você não se entrega facilmente e prefere a solitude a relações superficiais. Quando se apaixona, busca uma conexão de alma, espiritual e intelectual. No entanto, o seu padrão de autossabotagem é a idealização do parceiro e o medo de intimidade real: você pode colocar barreiras invisíveis para proteger a sua vulnerabilidade e afastar quem tenta chegar muito perto emocionalmente.",
      "cura": "Para curar suas relações, você precisa aprender que a intimidade real exige o risco de se machucar. Não espere que o parceiro adivinhe o que você sente apenas porque você é intuitiva. Comunique suas necessidades emocionais diretamente. Permita que a barreira do mistério caia para dar lugar à vulnerabilidade da vida a dois cotidiana."
    },
    "carreira": {
      "visao": "Profissionalmente, você se destaca em carreiras que envolvem psicologia, aconselhamento, artes, saúde, pesquisa, espiritualidade ou educação. Você tem um talento natural para ser mentora ou conselheira de bastidores (a inteligência estratégica sutil). Você prospera em ambientes calmos que respeitam o seu ritmo e não exige competição agressiva.",
      "escassez": "Sua escassez financeira pode vir da dificuldade em cobrar pelo seu trabalho ou em materializar suas ideias no plano físico. Como você valoriza muito o intangível, a espiritualidade e o conhecimento, pode sentir uma culpa inconsciente em ganhar dinheiro e prosperar materialmente. A cura financeira está em entender que o dinheiro é energia neutra que apoia a sua missão terrena."
    },
    "heranca": {
      "ancestralidade": "Carregar a energia da Sacerdotisa em seus sobrenomes de família indica uma herança mística extraordinária: você pertence a uma linhagem de mulheres e homens intuitivos, conectados com a espiritualidade e o ocultismo (muitas vezes rotulados como bruxos, curadores ou sensitivos). A egrégora familiar da Sacerdotisa no sobrenome atua como um escudo protetor sutil na sua vida. No entanto, o padrão a ser curado é o silenciamento de voz: a dor de antepassados que precisaram esconder sua espiritualidade, dons ou segredos para sobreviver. Você carrega essa energia para liberar os segredos da família e assumir seu poder espiritual à luz do dia, sem medo."
    }
  },
  "3": {
    "nome": "A Imperatriz",
    "geral": {
      "simbolismo": "Na carta da Imperatriz no Tarot Rider-Waite, uma bela mulher grávida e coroada com doze estrelas está sentada confortavelmente em tronos macios no meio de um campo de trigo dourado e abundante, ao lado de uma floresta cortada por um rio caudaloso. Um escudo em formato de coração com o símbolo de Vênus repousa aos seus pés. Seus mantos são decorados com romãs (símbolo da fertilidade). A Imperatriz é o arquétipo da Mãe Natureza, da criatividade ilimitada, do prazer de viver, da sensualidade, da nutrição e do crescimento próspero. Ela é a energia que faz as sementes germinarem e gerarem frutos reais.",
      "identidade": "Seu primeiro nome carrega a vibração exuberante da Imperatriz. Isso significa que a sua essência é magnética, criativa, acolhedora e vibrante. Você nasceu com um dom inato de embelezar a vida, expandir o que toca e nutrir projetos e pessoas. Sua mente é fértil: você tem ideias constantemente e possui uma conexão natural com o prazer, o conforto e a estética. Você é uma líder que atrai e inspira pela simpatia e pelo calor humano, não pela imposição. As pessoas sentem prazer em estar ao seu lado porque você emana uma energia de vida abundante e acolhimento materno.",
      "sombra": "A sombra da Imperatriz reside no excesso de controle, na dependência emocional e na necessidade constante de validação externa. Quando na sombra, você pode se tornar excessivamente protetora, tentando resolver a vida de todos e cobrando atenção e gratidão em troca. Há também uma tendência ao drama emocional e à vaidade desmedida, ou, no outro extremo, ao relaxamento excessivo e preguiça, esperando que os outros resolvam os seus problemas práticos.",
      "evolucao": "O seu caminho de evolução consiste em aprender a nutrir a si mesma antes de tentar nutrir o mundo. Estabeleça limites saudáveis nas suas relações e não tente controlar o destino das pessoas que ama. Canalize a sua imensa energia criativa para projetos autorais que expressem a sua própria voz, assumindo a independência emocional que a verdadeira rainha possui."
    },
    "amor": {
      "comportamento": "No amor, a Imperatriz é apaixonada, magnética, afetuosa e busca o prazer sensorial e a conexão romântica plena. Você gosta de mimar o parceiro e criar um lar acolhedor. No entanto, o seu padrão de autossabotagem é a tendência a agir como 'mãe' do parceiro, assumindo responsabilidades que não são suas e matando a atração sexual no processo.",
      "cura": "Para curar as suas relações, lembre-se de que um relacionamento saudável é feito entre dois adultos iguais. Deixe que o outro assuma as próprias responsabilidades e erre se for necessário. Equilibre o doar e o receber para que você não termine exausta e ressentida."
    },
    "carreira": {
      "visao": "Profissionalmente, você brilha em qualquer área ligada à comunicação, design, moda, beleza, nutrição, eventos, educação, artes ou em posições de liderança onde possa gerenciar pessoas com empatia. Você é excelente em dar início e expandir negócios. O dinheiro flui para você quando você se permite desfrutar do trabalho e focar no valor estético e humano do que faz.",
      "escassez": "A autossabotagem financeira da Imperatriz pode vir do consumismo emocional: gastar dinheiro para preencher vazios afetivos ou para manter uma imagem de status e generosidade com os outros. A cura da sua vida financeira reside em associar a prosperidade à estabilidade e ao crescimento sustentável, e não ao gasto impulsivo."
    },
    "heranca": {
      "ancestralidade": "Ter a Imperatriz em seus sobrenomes de família revela uma linhagem ancestral caracterizada pelo acolhimento, pela força feminina curadora, pela fartura na mesa e pelo amor à família. Seus antepassados provavelmente eram o ponto de união da família, conhecidos pela hospitalidade e generosidade. O padrão herdado que você precisa curar, no entanto, é o do sacrifício feminino: a crença de que as mulheres da família devem anular seus próprios desejos e sonhos para servir aos outros. Você carrega essa energia para mostrar que a prosperidade e a realização pessoal feminina não exigem o sacrifício da própria identidade."
    }
  },
  "4": {
    "nome": "O Imperador",
    "geral": {
      "simbolismo": "Na carta do Imperador no Tarot Rider-Waite, um homem maduro e de olhar firme está sentado em um trono de pedra decorado com quatro cabeças de carneiro (símbolo de Áries/iniciativa). Ele veste uma armadura de metal sob seus mantos vermelhos, segura um cetro de Ankh (símbolo da vida) em sua mão direita e um globo na esquerda. Ao fundo, montanhas áridas e vermelhas se erguem sob um céu alaranjado, simbolizando resiliência, território protegido e a solidez da estrutura criada pelo homem. O Imperador representa o arquétipo da liderança firme, da estabilidade material, da ordem social, da autoridade justa, da proteção e da capacidade de executar regras claras para que os projetos cresçam de forma segura.",
      "identidade": "Seu primeiro nome traz a vibração sólida e firme do Imperador. Sua essência é estruturada, lógica, focada e pragmática. Você é a pessoa com quem as outras contam quando o caos se instala; sua presença transmite segurança e estabilidade instantaneamente. Você tem um talento natural para planejar, organizar processos e executar tarefas difíceis com disciplina e resiliência. Você valoriza o respeito, o profissionalismo e a justiça. Seu propósito de vida está muito ligado à construção de bases sólidas para si e para aqueles sob a sua responsabilidade.",
      "sombra": "A sombra do Imperador se manifesta no autoritarismo, na rigidez mental e no medo de perder o controle. Você pode se tornar uma pessoa inflexível, que tem dificuldade em aceitar opiniões diferentes ou em demonstrar vulnerabilidade e sentimentos. A sombra do Imperador também gera o padrão do 'crítico interno implacável': você se cobra tanto e exige tanta perfeição de si mesmo que acaba travando ou se tornando duro demais com os erros alheios.",
      "evolucao": "O seu caminho de evolução consiste em aprender a flexibilizar as suas regras mentais. Entenda que a verdadeira liderança não vem do controle rígido, mas do exemplo inspirador e do acolhimento. Permita-se relaxar as defesas e demonstrar que você também é humano, que sente medo ou cansaço. Aprenda a delegar tarefas e confiar na inteligência e capacidade das outras pessoas."
    },
    "amor": {
      "comportamento": "No amor, o Imperador é protetor, provedor, extremamente leal e busca estabilidade e compromisso sério. Você demonstra afeto através de atitudes práticas (cuidando do lar, dando segurança financeira) mais do que com palavras doces. Sua autossabotagem é a tendência a controlar a rotina e as decisões do parceiro, ou afastar a intimidade emocional por medo de parecer vulnerável.",
      "cura": "Para curar as suas relações, você precisa permitir que o amor seja um espaço de entrega emocional, e não de gerenciamento. Lembre-se de que a pessoa ao seu lado quer a sua presença e o seu coração aberto, não apenas o seu suporte lógico. Aprenda a dizer 'eu te amo' e expresse o seu afeto com toques e palavras suaves."
    },
    "carreira": {
      "visao": "Profissionalmente, você nasceu para ocupar posições de diretoria, gerência, administração ou para ter a sua própria empresa estruturada. Você é excelente para colocar ordem no caos, criar regras justas e planejar metas de longo prazo. O dinheiro é visto por você como ferramenta de liberdade, território e poder de ação. Você prospera na estabilidade e no crescimento linear e ético.",
      "escassez": "Sua autossabotagem financeira reside na rigidez absoluta e no medo paralisante de perder o controle do dinheiro. Você pode economizar excessivamente ou travar diante de investimentos ousados por medo da instabilidade. A cura da escassez está em entender que a prosperidade exige movimento, e que a segurança absoluta não existe: a flexibilidade inteligente é a sua maior aliada."
    },
    "heranca": {
      "ancestralidade": "Ter o Imperador em seus sobrenomes familiares revela uma egrégora ancestral ligada ao trabalho duro, à disciplina militar ou administrativa, e à construção de patrimônio com base na ética e esforço físico. Seus antepassados provavelmente foram os pilares de sustentação de famílias inteiras, pessoas que abriram mão de seus sentimentos para poder prover e proteger. A sombra que você herda para curar é o padrão do silenciamento emocional dos homens e mulheres da família. Você carrega essa energia para mostrar que é possível liderar, estruturar e prosperar sem precisar fechar o coração e sem o peso do sofrimento silencioso."
    }
  },
  "5": {
    "nome": "O Papa / O Hierofante",
    "geral": {
      "simbolismo": "Na carta do Papa (ou O Hierofante) no Tarot Rider-Waite, ele está sentado em um trono de pedra entre duas colunas clássicas de um templo. Ele usa uma tiara de três níveis, veste mantos cerimoniais azuis e vermelhos e segura um cetro triplo em sua mão esquerda. Sua mão direita está erguida em um gesto de bênção direcionado a dois iniciados ajoelhados aos seus pés. Duas chaves cruzadas (as chaves dos mistérios da vida) repousam no chão diante dele. O Papa representa a ponte entre a sabedoria divina e as estruturas humanas. Ele simboliza o arquétipo do educador, do mentor espiritual, dos valores tradicionais bem fundamentados, do estudo filosófico e da transmissão do conhecimento prático para guiar a jornada de evolução da humanidade.",
      "identidade": "Seu primeiro nome vibra na frequência do Papa. Sua essência é de um transmissor de sabedoria, conselheiro inato e pacificador. Desde cedo, você tem uma curiosidade profunda sobre o funcionamento da mente, da filosofia, das religiões e do comportamento humano. Você busca um sentido maior para tudo o que faz. Sua fala tem peso: as pessoas naturalmente te respeitam e pedem seus conselhos porque sentem a solidez do seu caráter. Seu propósito está muito ligado a ensinar, orientar e criar caminhos de aprendizado para que os outros encontrem seu próprio rumo na vida prática.",
      "sombra": "A sombra do Papa é o dogmatismo, o moralismo e a arrogância intelectual. Você pode cair na armadilha de acreditar que a sua visão de mundo é a única correta ou que possui respostas absolutas para a vida alheia. A sombra também se manifesta no apego excessivo às normas sociais ('o que os outros vão pensar') e na dificuldade em quebrar padrões antigos, mantendo-se preso a estruturas falidas apenas por medo de ousar ou inovar.",
      "evolucao": "O seu caminho de evolução pede que você seja um eterno estudante e não apenas o detentor da verdade. Mantenha a mente aberta para novas ideias e ouça ativamente opiniões contrárias com humildade. Use a sua sabedoria para libertar e empoderar as pessoas, e não para criar regras rígidas de comportamento. Lembre-se: o verdadeiro mestre ensina a pensar, e não o que pensar."
    },
    "amor": {
      "comportamento": "No amor, o Papa busca um relacionamento estruturado com valores, respeito e metas de vida compartilhadas. Você é leal, protetor e valoriza a rotina saudável e o crescimento mútuo. Sua autossabotagem é tentar 'ensinar' ou 'corrigir' o parceiro constantemente, agindo como um mentor intelectual em vez de ser um companheiro afetivo e espontâneo.",
      "cura": "Para curar as suas relações, saia do papel de professor. O amor íntimo precisa de conexão real de pele e emoção, não de regras morais. Aprenda a aceitar o parceiro como ele é, com suas imperfeições, e permita-se viver momentos de espontaneidade leve e divertida sem julgamento."
    },
    "carreira": {
      "visao": "Profissionalmente, você se destaca na educação, consultoria, psicologia, direito, escrita, liderança espiritual, treinamento ou em qualquer função corporativa estruturada onde precise organizar e transmitir conhecimentos complexos. O dinheiro é atraído para a sua vida através da autoridade intelectual e da credibilidade ética que você constrói.",
      "escassez": "Sua autossabotagem financeira está ligada à síndrome do impostor: você pode achar que nunca está 'pronto' ou 'estudado' o suficiente para cobrar o valor real do seu serviço. A cura financeira está em confiar na sabedoria que você já acumulou na prática e parar de buscar certificações infinitas como desculpa para não se posicionar comercialmente."
    },
    "heranca": {
      "ancestralidade": "Ter o Papa nos seus sobrenomes indica uma linhagem ancestral associada à busca do conhecimento, à manutenção da ordem moral e familiar, ou ao ensino tradicional. Sua família provavelmente valoriza muito o estudo, o status social ou a ética rígida. A sombra familiar a ser curada por você é o medo do escândalo e as aparências sociais limitadoras. Você carrega essa energia para mostrar que a verdadeira sabedoria espiritual e a evolução individual são mais importantes do que apenas cumprir expectativas familiares engessadas."
    }
  },
  "6": {
    "nome": "Os Enamorados",
    "geral": {
      "simbolismo": "Na carta dos Enamorados no Tarot Rider-Waite, um homem e uma mulher nus (representando Adão e Eva em estado de pureza original) estão sob a bênção de um grande anjo com asas de fogo (o arcanjo Rafael), que surge acima das nuvens. Ao fundo, a árvore da vida com doze frutos fica atrás do homem, e a árvore do conhecimento do bem e do mal (com a serpente enrolada) fica atrás da mulher. Uma grande montanha vulcânica se ergue entre eles. A carta representa não apenas o amor romântico, mas a energia do livre-arbítrio, o poder de escolha consciente, a harmonia dos opostos (razão e emoção, masculino e feminino) e a necessidade de tomar decisões com base nos valores do coração, e não na aprovação externa.",
      "identidade": "Seu primeiro nome vibra na frequência dos Enamorados. Sua essência é relacional, harmoniosa, estética e extremamente empática. Você nasceu com uma sensibilidade fina para captar os sentimentos dos outros e busca a harmonia em todas as suas interações. A arte da escolha é a sua grande jornada na vida: você é uma pessoa movida por paixão e autenticidade em tudo o que faz. Seu propósito está ligado a criar conexões profundas, unir pessoas, mediar conflitos e viver de acordo com suas próprias verdades fundamentais, aprendendo a decidir por si mesma.",
      "sombra": "A sombra dos Enamorados se manifesta na indecisão crônica, no medo do conflito e no hábito de tentar agradar a todos, anulando a própria voz. Você pode travar diante de escolhas importantes por medo de perder opções ou desapontar as pessoas à sua volta. Outro traço de sombra é a dependência emocional excessiva, o medo de ficar só ou a tendência de se anular em prol de manter a paz superficial nas relações.",
      "evolucao": "Seu caminho de evolução exige que você desenvolva o autodomínio e a coragem de fazer escolhas firmes, aceitando que escolher um caminho significa necessariamente abrir mão de outro. Cultive a sua independência emocional e aprenda a dizer 'não' quando a sua verdade interna for agredida. A verdadeira harmonia só existe quando há espaço para a sua própria identidade viva."
    },
    "amor": {
      "comportamento": "No amor, o arquétipo dos Enamorados é o mais romântico e magnético de todos. Você busca fusão de almas, carinho físico, reciprocidade profunda e beleza na relação. Você valoriza o namoro e a parceria diária. Sua autossabotagem é o medo paralisante da rejeição e a tendência a aceitar dinâmicas desiguais de afeto apenas para manter a pessoa amada por perto.",
      "cura": "Para curar as suas relações, você precisa se posicionar. Não aceite menos do que você entrega. O amor verdadeiro respeita a sua individualidade; se você precisa se anular para caber na vida do outro, essa conexão está desequilibrada. Aprenda a amar a si mesma primeiro para atrair parcerias maduras."
    },
    "carreira": {
      "visao": "Profissionalmente, você prospera em áreas ligada a parcerias, relações públicas, vendas consultivas, recursos humanos, moda, design, psicologia ou mediação de conflitos. Você é excelente em trabalhar em equipe e gerar ambientes de cooperação. O dinheiro vem da sua habilidade de se conectar de forma autêntica e empática com as pessoas.",
      "escassez": "Sua autossabotagem financeira está ligada à dificuldade em cobrar de forma assertiva ou na falta de limites em parcerias comerciais. Você pode fazer descontos excessivos ou trabalhar de graça por medo de constranger o cliente. A cura financeira está em entender que cobrar o preço justo pelo seu serviço é um ato de respeito e autoamor."
    },
    "heranca": {
      "ancestralidade": "Ter os Enamorados em seus sobrenomes revela uma egrégora ancestral conectada à importância da união familiar, ao afeto demonstrado e à busca de parcerias de sucesso na história da família. Seus antepassados provavelmente eram pessoas queridas no círculo social, unidas pelo amor familiar. O padrão herdado que você precisa curar é a tendência da família a evitar conflitos reais varrendo as discussões sérias para baixo do tapete para manter uma aparência de harmonia. Você carrega essa energia para liberar a família das verdades não ditas e ensinar que a verdadeira união suporta a honestidade."
    }
  },
  "7": {
    "nome": "O Carro",
    "geral": {
      "simbolismo": "Na carta do Carro no Tarot Rider-Waite, um jovem guerreiro coroado está em pé dentro de uma carruagem adornada com um dossel azul cravejado de estrelas. Em seus ombros, há luas crescentes (representando as emoções), e ele veste uma armadura marcada com símbolos alquímicos. Ele não segura rédeas, mas sim uma varinha, controlando a carruagem através da pura força de vontade e foco mental. Diante do carro, repousam duas esfinges, uma preta e outra branca, que puxam para direções opostas. O Carro representa o arquétipo do foco inabalável, da determinação, da vitória sobre as adversidades, da direção clara e da capacidade de dominar as próprias contradições internas para acelerar o progresso material e pessoal.",
      "identidade": "Seu primeiro nome traz a velocidade e determinação do Carro. Sua essência é de um conquistador, uma pessoa focada, ambiciosa e com grande impulso de realização prática. Você tem uma resiliência de aço: quando define uma meta, assume o comando e avança apesar de qualquer obstáculo. Você busca independência e controle sobre o seu próprio destino. Seu propósito de vida está fortemente ligado a vencer desafios difíceis, viajar, mudar de ambientes e liderar projetos que exijam direcionamento assertivo e clareza de foco no progresso material.",
      "sombra": "A sombra do Carro é o esgotamento físico, a pressa crônica, a agressividade e a dificuldade em lidar com a frustração. Você pode se tornar uma pessoa impaciente e controladora, que tenta 'atropelar' as circunstâncias e os limites físicos do seu próprio corpo para obter resultados rápidos. A sombra também se manifesta no medo paralisante de perder o rumo das coisas, o que gera ansiedade crônica e dificuldade para relaxar e confiar no fluxo da vida.",
      "evolucao": "O seu caminho de evolução pede que você aprenda que nem tudo pode ser controlado pela força de vontade. Desenvolva a flexibilidade: às vezes, desviar do obstáculo é mais inteligente do que tentar quebrar a parede com a cabeça. Aprenda a ouvir e respeitar o ritmo das outras pessoas e cultive momentos de pausa estruturada para evitar a exaustão física e mental."
    },
    "amor": {
      "comportamento": "No amor, o Carro busca parceiros que tenham metas de vida compatíveis e que queiram crescer e prosperar juntos. Você é protetor, direto em suas intenções e gosta de liderar a dinâmica da relação. Sua autossabotagem é a pressa em consolidar as coisas ou tratar o relacionamento como um projeto corporativo a ser gerenciado, gerando atrito pela falta de sensibilidade e toque afetivo suave.",
      "cura": "Para curar as suas relações, solte a necessidade de ter sempre a razão ou o controle do caminho do casal. O relacionamento exige o compartilhamento das rédeas. Desenvolva a escuta ativa e dê espaço para que o parceiro expresse seus sentimentos sem que você encare isso como um problema prático a ser resolvido com urgência."
    },
    "carreira": {
      "visao": "Profissionalmente, você se destaca em cargos de alta performance, vendas diretas, gestão de tráfego, empreendedorismo acelerado, logística, ou projetos que exijam metas agressivas. Você tem sangue frio sob pressão. O dinheiro flui quando você foca em expandir horizontes e criar canais de vendas organizados com metas de tração rápidas.",
      "escassez": "Sua autossabotagem financeira é a impulsividade nos gastos motivada pela pressa de crescer ou demonstrar sucesso material. Você pode assumir riscos financeiros excessivos por autoconfiança desmedida. A cura da sua vida financeira está na construção de reservas sólidas de médio prazo e na paciência estratégica para investimentos."
    },
    "heranca": {
      "ancestralidade": "Ter o Carro em seus sobrenomes revela uma linhagem ancestral de migrantes, desbravadores, pessoas que saíram de suas terras natas com foco na sobrevivência e no progresso. Sua família carrega o DNA da vitória prática sobre as adversidades materiais e geográficas. O padrão familiar que você herda para curar é a pressa constante e o vício em trabalho (workaholic): a sensação de que se você parar para descansar, a vida vai dar errado. Você carrega essa energia para ensinar ao seu clã familiar que prosperar também inclui o direito ao repouso e ao desfrute."
    }
  },
  "8": {
    "nome": "A Justiça",
    "geral": {
      "simbolismo": "Na carta da Justiça no Tarot Rider-Waite, uma figura solene está sentada em um trono de pedra entre duas colunas maciças, sob um pano de fundo avermelhado. Em sua mão direita, ela segura uma espada erguida de dois gumes, simbolizando o discernimento mental agudo que corta as ilusões. Em sua mão esquerda, ela segura a balança, demonstrando equilíbrio, ponderação e a lei de causa e efeito. Ela usa uma coroa dourada com um pequeno quadrado vermelho no centro (representando a ordem e a matéria) e expõe um pé sob a túnica verde, mostrando a sua conexão com a base da realidade terrestre. A Justiça representa o arquétipo da integridade ética, do equilíbrio racional, da clareza analítica, da responsabilidade pessoal e da colheita justa: você recebe exatamente o que planta na vida.",
      "identidade": "Seu primeiro nome vibra na frequência da Justiça. Sua essência é regida pela clareza, ética, discernimento, senso de verdade e equilíbrio racional. Você é aquela pessoa que naturalmente busca a verdade nas situações e detesta a injustiça ou a manipulação. Sua mente é analítica e lógica; você tem facilidade para pesar prós e contras e decidir com base em fatos reais. As pessoas respeitam o seu posicionamento porque sabem que você é íntegro e direto em suas palavras. Seu propósito está ligado a colocar ordem nas situações, tomar decisões cruciais e ensinar limites saudáveis.",
      "sombra": "A sombra da Justiça se manifesta na autocrítica impiedosa, no perfeccionismo paralisante e na frieza emocional. Você pode se cobrar tanto para ser 'justo' e 'perfeito' que acaba se bloqueando para não cometer erros. Há também uma tendência a julgar as pessoas de forma dura e intransigente, esquecendo que o comportamento humano também é feito de emoções e falhas comuns, gerando isolamento afetivo pelo excesso de exigência com os outros.",
      "evolucao": "Seu caminho de evolução pede que você integre a compaixão e o perdão à sua espada de discernimento. Entenda que a verdade real inclui a vulnerabilidade emocional humana. Seja mais gentil consigo mesmo e com as falhas alheias. Use a sua capacidade de organização e análise para estruturar a vida de forma leve, e não para criar tribunais de cobrança mental diária."
    },
    "amor": {
      "comportamento": "No amor, a Justiça busca igualdade de direitos e deveres, respeito mútuo, clareza e fidelidade absoluta. Você é direto e não suporta joguinhos emocionais ou traições. No entanto, o seu padrão de autossabotagem é a frieza de posicionamento: você pode criar uma barreira lógica de proteção nas discussões, evitando demonstrar mágoas para não parecer 'irracional' ou vulnerável perante o parceiro.",
      "cura": "Para curar as suas relações, lembre-se de que o amor íntimo é regido pela conexão emocional e pelo afeto, não por um contrato de deveres matemáticos. Permita-se errar e aceitar o parceiro mesmo quando ele falhar logicamente. Substitua a cobrança severa pela conversa acolhedora."
    },
    "carreira": {
      "visao": "Profissionalmente, você brilha em posições que exijam auditoria, direito, contabilidade, gestão de contratos, análise técnica detalhada, ou em qualquer setor corporativo estruturado onde a precisão de dados seja vital. O dinheiro para você vem da entrega honesta, da reputação inabalável e da prestação de serviços organizados e éticos.",
      "escassez": "Sua autossabotagem financeira reside no medo obsessivo de dever dinheiro ou de ser cobrado injustamente, o que pode te paralisar e fazer com que você evite dar passos ousados de investimento ou parcerias comerciais. A cura financeira está em entender o dinheiro como energia de troca livre e abundante, estruturando seu caixa com inteligência sem medo paralisante da escassez."
    },
    "heranca": {
      "ancestralidade": "Ter a Justiça em seus sobrenomes revela uma egrégora familiar ancestral ligada à preservação da honra, à reputação pública ilibada, ao cumprimento de deveres ou à dor de injustiças históricas sofridas. Seus antepassados provavelmente precisaram trabalhar duro para provar seu valor moral perante a sociedade. O padrão de sombra que você herda para curar é a cobrança interna severa herdada de pais e avós: a crença de que você só tem valor se for perfeito. Você carrega essa energia para liberar a sua linhagem desse peso, ensinando que a vida também é feita de leveza e aceitação das fraquezas humanas."
    }
  },
  "9": {
    "nome": "O Eremita",
    "geral": {
      "simbolismo": "Na carta do Eremita no Tarot Rider-Waite, uma figura idosa, vestindo uma túnica cinza com capuz, está solitária no topo de uma montanha coberta de neve sob um céu escuro. Em sua mão direita, ele segura uma lanterna dourada que brilha com uma estrela de seis pontas (a Estrela de Davi - símbolo da sabedoria), e em sua mão esquerda ele segura um cajado de madeira (o apoio da experiência terrena). O Eremita representa o arquétipo da introspecção profunda, da busca pela verdade interior, do autoconhecimento isolado, do tempo que amadurece os projetos e da sabedoria silenciosa. A sua lanterna brilha apenas para o próximo passo no caminho, ensinando que a evolução espiritual e a clareza prática acontecem passo a passo, no silêncio da própria alma.",
      "identidade": "Seu primeiro nome vibra na frequência do Eremita. Sua essência é introspectiva, profunda, sábia, madura e extremamente reflexiva. Você é aquela pessoa que tem uma maturidade precoce; desde a juventude, parece carregar a alma de um idoso sábio. Você necessita do isolamento físico para se conectar com a sua própria mente e organizar as suas ideias. Você tem facilidade para estudar a fundo assuntos complexos e é o guardião de saberes profundos. Seu propósito está ligado a iluminar o caminho das pessoas através do seu exemplo de integridade silenciosa, agindo como um farol de autoconhecimento no mundo.",
      "sombra": "A sombra do Eremita é o isolamento defensivo, o orgulho de se manter distante das pessoas ('as pessoas são muito superficiais') e o ceticismo intelectual. Você pode cair no padrão de se afastar do convívio social por medo de ser incompreendido ou rejeitado, tornando-se uma pessoa solitária, rígida, ranzinza ou excessivamente fechada. O maior perigo da sombra é a solidão crônica disfarçada de independência intelectual sagrada.",
      "evolucao": "Seu caminho de evolução exige que você desça da montanha de isolamento e compartilhe a sua luz com o mundo. Não guarde a sua sabedoria apenas para si mesmo. A verdadeira evolução espiritual e humana acontece nas interações diárias, nas trocas com os outros e na vulnerabilidade do convívio. Aprenda a confiar nas pessoas e cultive relações de afeto prático, saindo do casulo mental."
    },
    "amor": {
      "comportamento": "No amor, o Eremita busca conexões sérias, calmas e profundas baseadas no companheirismo silencioso e na maturidade. Você valoriza o próprio espaço e detesta cobranças impulsivas ou parceiros barulhentos demais. Sua autossabotagem é erguer muralhas de silêncio intransponíveis perante o parceiro nas crises, preferindo se retirar a debater a dor juntos, o que afasta o outro emocionalmente.",
      "cura": "Para curar as suas relações, você precisa aprender a abrir a sua lanterna para o parceiro. Comunique o seu sentimento íntimo em vez de se trancar no quarto da sua mente. Aceite que o amor conjugal exige dividir o território físico e emocional, respeitando as necessidades de convívio saudável do outro."
    },
    "carreira": {
      "visao": "Profissionalmente, você se destaca em atividades de pesquisa profunda, escrita, análise detalhada, programação, áreas de saúde mental, mentoria individual ou qualquer função especializada que exija estudo concentrado de longo prazo. O dinheiro é atraído para você pela sua autoridade profissional construída com discrição e foco na qualidade impecável.",
      "escassez": "Sua autossabotagem financeira está ligada à escassez de movimento: você pode demorar muito tempo planejando, pesquisando ou aprimorando seu produto/serviço por achar que 'ainda não está perfeito', perdendo oportunidades comerciais incríveis pela lentidão na ação. A cura da sua vida financeira está na velocidade de execução prática."
    },
    "heranca": {
      "ancestralidade": "Ter o Eremita em seus sobrenomes revela uma linhagem ancestral caracterizada pelo silêncio, pelo recolhimento protetor, pela resiliência solitária e pelo valor da herança intelectual ou espiritual silenciosa. Sua família provavelmente tem o histórico de pessoas discretas, que mantiveram seus segredos e dores guardados na alma. A sombra familiar a ser curada por você é o padrão de solidão e o tabu da comunicação afetiva entre pais e filhos. Você carrega essa energia para ensinar ao seu clã que demonstrar amor, falar de sentimentos e quebrar o silêncio da casa é seguro e liberta."
    }
  }
};

module.exports = conteudoArquetipos;
